version: '3.7'

services:
  frontend:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "yarn && yarn start"
    environment:
      REACT_APP_DEV: $DEV
    links:
      - server
  # test:
  #   build:
  #     context: .
  #   volumes:
  #     - '.:/app'
  #   command: bash -c "yarn && yarn test"
  server:
    image: node:latest
    volumes:
      - .:/server
    working_dir: /server
    ports:
      - 9000:9000
    command: bash -c "cd server && yarn && yarn start"